### ISSUE TITLE
Scaling issues, no CLI installer, what is this?

### ISSUE THREAD

**Issue by alexlyee** [archcraft-os/archcraft-wayland-special#1]
Hey, I bought your OS wanting to try it out a few weeks ago, and you still haven't replied to any of my emails. No matter what I do, I don't see any CLI installer for wayland special. Only Calamares. I'm booting on an AMD cpu + gpu w/ a 4k monitor and all but the River session is downright unusable, whether the text is super tiny or it simply won't let me open the app panel at all. I'm about ready to ask for a refund if this doesn't work. Super frustrating to not hear back for weeks

**Comment by adi1090x** [comment]
The CLI installer was not added in the first ISO. It's now added in NEW  ISO.
Wayland compositors have better support for multi-monitors and scaling. You just needed to edit the config files accordingly.

PS: I've replied to all the mails i ever got. For some reason, I've got your email.
