### ISSUE TITLE
Macbook Pro no right click / middle click menu with Hyprland

### ISSUE THREAD

**Issue by GordonFR24** [archcraft-os/archcraft-wayland-special#10]
Macbook Pro Early 2015, all other work fine out of the box aside from Hyprland compositor. 

I was only able to test MacOS on the MBP A1502
Possibly libinput?

**Comment by adi1090x** [comment]
There is not such menus in a tiling WM/WC generally. Few WMs (like openbox, Fluxbox) provides this, But No Wayland Compositor.
