### ISSUE TITLE
add openbox and bspwm among others

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft-wayland-special#11]
I don't want to buy this iso because they are not in this iso (your screenshot doesn't show them, that's why I think so).

**Comment by Cir-0** [comment]
But openbox and bspwm aren't Wayland compositors, they are X11 window managers, so I think it would go against the purpose of the ISO. Is there a particular reason you need an ISO for these? I purchased the new premium i3 config and the install package includes (almost) all needed dependencies, I'd imagine that the premium openbox and bspwm configs include the same. I haven't used it a ton yet, but the only thing I needed to manually install and configure so far is a polkit agent. If you're unfamiliar with them, this is a good resource that helped me out: https://wiki.archlinux.org/title/Polkit

**Comment by adi1090x** [comment]
Soon, A new ISO is coming.
