### ISSUE TITLE
Login session

### ISSUE THREAD

**Issue by encoreeencore** [archcraft-os/archcraft-wayland-special#12]
Hello
I try to install wayland iso but i cannot access to the desktop
sway and other is blocking after login and hyprland restart login
I try all the options no nouveau, nvidia...but nothing happens
I forgot to say that the problems were on the tower, in my laptops it is very good. I haven't installed it yet because I was mainly thinking of installing it on the desktop. I would like to know what is the problem. Thank you

**Comment by hzm170** [comment]
from what i seen is: WARNING : This ISO will not work with Nvidia (using proprietary graphics drivers) 
as i have "Nvidia" as well and does not work to, but tbh he should find a way to allow "Nvidia" to work so it can be more better to use..

**Comment by adi1090x** [comment]
Try the Latest ISO (April). I've added Nvidia support to it, So it can (possibly) work on Nvidia Machines.

**Comment by adi1090x** [comment]
Reopen if needed

**Comment by xxnuo** [comment]
Had the same problem on my 2 laptop.
ISO version: October 15th, 2023
1: Xiaomi pro 15.6
i7-8550u with Intel UHD 620 and NVIDIA MX250
2: Honor magicbook
i5-8250u with Intel UHD 620 and NVIDIA MX150

The motherboards cannot disable NVIDIA graphics card, although I am using the latest archcraftiso and still encounter the above problem.
Is this series of cards not supported yet?
