### ISSUE TITLE
Cannot access Ko-Fi

### ISSUE THREAD

**Issue by glow12121** [archcraft-os/archcraft-wayland-special#13]
Hi,

I have tried to access Ko-Fi to see the price of Archcraft Wayland and Wayfire a few times within the last several weeks. But it never works for me.

I am currently in  Russia. Could this be the reason. I haven't found any information on the Internet about Ko-Fi blocking Russian residents though.

Are there other websites where one can buy the distro? 

Thanks in advance.

**Comment by adi1090x** [comment]
Paypal discontinued it's services in Russia, i guess.
