### ISSUE TITLE
Blackscreen and no configuration files

### ISSUE THREAD

**Issue by WayneY** [archcraft-os/archcraft-wayland-special#2]
After installed the wayland-special iso, no matter which wm I choose, all of them are blackscreen.

I read the documents in your website, but appearently you did not write a wayland-speical document. The picom is an Xorg compositor, no use for wayland, and ofcourse no such a file exists in the  ~/.config.

Besides, I can't see any configuration files for wms in my ~/.config.  During the installation I mounted another disk to /home, I don't know if this caused the trouble.

Now I am trying to reinstall to pure Arch and then copy your dot files in the iso, wishing  it could work.

To be honest, I think your regular version (openbox, bspwm) has higher quanlity with this wayland special one. At least the network icon in the bar of regular version can detect  and list the ssid  of wifi automatically.  I paid this version mainly for time saving, but it seems  not so saving time yet.

**Comment by pophilpo** [comment]
Are you trying to boot using Nvidia GPU?

**Comment by WayneY** [comment]
@pophilpo  Yes but although I have a Nvidia card on my board, I also have an intel GPU.  When I install a pure Arch by using the script of archinstall I have a choice to pick the drivers and I usually pick the "all open source drivers" option and it works fine.  Howerver in this calamares version seems either I don't have such a choice or it is unable to install a proper driver automatically.  This is not a problem can't be solved. Endeavouros also provides a calamares version with sway, but runs without any troubles.

**Comment by pophilpo** [comment]
@WayneY I had an impression that you couldn't even login into liveusb having a black screen. I had this problem and I fixed it by passing` nvidia_drm.modeset=1 ` kernel option. This helped me to actually login into any WM (tested with river and hyprland). But this is not a very good thing to do, you may experience some glitches with Nvidia + wayland. Unfortunately at the moment nvidia doesn't really work well with wayland  and it was stated in the archcraft wayland edition repo: "This ISO may or may not work with Nvidia (using proprietary graphics drivers)".

**Comment by WayneY** [comment]
@pophilpo Why do you think I cannot login into the liveusb? What I suffer blackscreen is the installed version on the machine, not the liveusb. And why should I set that option when I don't even need a nvidia driver at all? I can go with Intel + Wayland. Having a Nvidia card on the machine doesn't mean you should always enable it.

**Comment by adi1090x** [comment]
@WayneY I've Updated the ISO. You can use the updated one.

Btw, I've already mentioned about Nvidia situation with wayland, If you still choose to go for it, I assume you know what you're going to deal with, which includes a lot of manual work-arounds to get it work on your machine, like @pophilpo mentioned, that it includes KMS, kernel parameters, init modules, hooks etc.
