### ISSUE TITLE
c ant open qt5ct

### ISSUE THREAD

**Issue by coutouly** [archcraft-os/archcraft-wayland-special#4]
`qt.qpa.plugin: Could not find the Qt platform plugin "wayland-egl" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[1]    30904 IOT instruction (core dumped)  qt5ct`

**Comment by Cir-0** [comment]
Installing the package qt5-wayland fixed this issue for me. I would also install qt6-wayland to prevent issues with Qt 6 apps.

**Comment by adi1090x** [comment]
Great!
