### ISSUE TITLE
Black Screen with blinking line after sign in page.

### ISSUE THREAD

**Issue by mholn** [archcraft-os/archcraft-wayland-special#7]
When I use the default session, it doesnt work, or if i use any of the other sessions, it just kicks me back to the login screen.

I use an NVIDIA RTX 2080 btw, if that helps.

**Comment by TropicLegend** [comment]
Same here.

**Comment by adi1090x** [comment]
Try the Latest ISO (April). I've added Nvidia support to it, So it can (possibly) work on Nvidia Machines.
